-- Active: 1689905826056@@server.perumoney.pe@3306@pm_homepage
CREATE DATABASE IF NOT EXISTS pm_homepage;
USE pm_homepage;
-- MALL
CREATE TABLE IF NOT EXISTS mall (
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state INT NOT NULL DEFAULT '1'
) ENGINE = InnoDB;
-- SERVICE
CREATE TABLE IF NOT EXISTS service (
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	code CHAR(5) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state INT NOT NULL DEFAULT '1'
) ENGINE = InnoDB;
-- AGENCY
CREATE TABLE IF NOT EXISTS agency (
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	mall VARCHAR(255) NOT NULL,
	department_id CHAR(36) NOT NULL,
	province_id CHAR(36) NOT NULL,
	district_id CHAR(36) NOT NULL,
	address VARCHAR(500) NOT NULL,
	lat CHAR(255) NOT NULL,
	lng CHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state INT NOT NULL DEFAULT '1'
) ENGINE = InnoDB;
-- ALT AGENCY
CREATE TABLE IF NOT EXISTS alt_agency (
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state INT NOT NULL DEFAULT '1'
) ENGINE = InnoDB;
-- DOCUMENT
CREATE TABLE IF NOT EXISTS document(
	id CHAR(36) PRIMARY KEY,
	code CHAR(20) NOT NULL,
	name VARCHAR(50) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state INT NOT NULL DEFAULT '1'
) ENGINE = InnoDB;
-- REQUEST
CREATE TABLE IF NOT EXISTS request(
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state INT NOT NULL DEFAULT '1'
) ENGINE = InnoDB;
-- UB DEPARTMENT
CREATE TABLE IF NOT EXISTS ub_department (
	id INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL
) ENGINE = InnoDB;
-- UB PROVINCE
CREATE TABLE IF NOT EXISTS ub_province (
	id INT PRIMARY KEY,
	name VARCHAR (50) NOT NULL,
	department_id INT NOT NULL
) ENGINE = InnoDB;
-- UB DISTRICT
CREATE TABLE IF NOT EXISTS ub_district (
	id INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	province_id INT NOT NULL
) ENGINE = InnoDB;
-- REQUEST HISTORY
CREATE TABLE IF NOT EXISTS request_history (
	id CHAR(36) PRIMARY KEY,
	serie char(5) NOT NULL,
	correlative char(5) NOT NULL,
	ruc char(11) NOT NULL,
	business VARCHAR(30) NOT NULL,
	document_id CHAR(36) NOT NULL,
	document_num CHAR(12) NOT NULL,
	first_name VARCHAR(30) NOT NULL,
	father_surname VARCHAR(30) NOT NULL,
	mother_surname VARCHAR(30) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone INT NOT NULL,
	address VARCHAR(200) NOT NULL,
	department_id CHAR(36) NOT NULL,
	province_id CHAR(36) NOT NULL,
	district_id CHAR(36) NOT NULL,
	service_id CHAR(36) NOT NULL,
	amount DECIMAL(10, 3) NOT NULL,
	request_id CHAR(36) NOT NULL,
	day TIMESTAMP NOT NULL,
	hour TIME NOT NULL,
	agency_id CHAR(36) NOT NULL,
	message VARCHAR(5000) NOT NULL,
	createad_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	state INT NOT NULL DEFAULT '1'
) ENGINE = InnoDB;