# Environtment
@BASE_URL=http://localhost:3000
@ROUTES=/api/v1/details-claims
@DOCUMENT=12345678
### Listar registros
GET {{BASE_URL}}{{ROUTES}}/ HTTP/1.1

### Listar registros por DOCUMENTO
GET {{BASE_URL}}{{ROUTES}}/{{DOCUMENT}} HTTP/1.1

### Crear registro pesona natural
POST {{BASE_URL}}{{ROUTES}} HTTP/1.1
Content-Type: application/json

{
  "documentId": "ebadefdd-4190-11ef-a402-723401d86a22",
  "documentNum": "12345678",
  "serviceId": "aff6c9e9-4191-11ef-a402-723401d86a22",
  "amount": "999.99",
  "claimsId":"72dd16e5-4191-11ef-a402-723401d86a22",
  "day": "2024/07/14",
  "hour": "12:00",
  "agencyId": "508765f3-4198-11ef-a402-723401d86a22",
  "message": "Mensaje de prueba desde el VSCode"
}
