# Environtment
@BASE_URL=http://localhost:3000
@ROUTES=/api/v1/documents-identity
@ID=ebadefdd-4190-11ef-a402-723401d86a22
### Listar registros
GET {{BASE_URL}}{{ROUTES}} HTTP/1.1

### Listar registros por ID
GET {{BASE_URL}}{{ROUTES}}/{{ID}} HTTP/1.1
