# Environtment
@BASE_URL=http://localhost:
@PORT=3000
@ROUTES=/api/v1/sendemail

### Listar registros
POST {{BASE_URL}}{{PORT}}{{ROUTES}} HTTP/1.1
Content-Type: application/json

{
  "email": "danielvaleriob@gmail.com",
  "history_id": "123",
  "typedoc": "DNI",
  "numberdoc": "46789226",
  "firstname": "FABRIZIO",
  "lastnamefather": "VALERIO",
  "lastnamemother": "FERRO",
  "phone": "999999999",
  "address": "CA. LAS FRESAS 123 SN - VILLA EL SALVADOR",
  "departament": "CALLAO",
  "province": "CALLAO",
  "district": "CALLAO",
  "service": "CAMBIO DE DIVISA",
  "amount": "999.99",
  "typerequest": "RECLAMO",
  "day": "2022-07-13",
  "hour": "12:00:00",
  "agency": "PLAZA NORTE",
  "message": "HELLO WORLD!"
}
